# Generated by Django 5.2.5 on 2025-09-02 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Precio Base')),
                ('comision_compra', models.DecimalField(decimal_places=3, default=0, help_text='Ingrese el valor en decimal (entre 0 y 1). Ejemplo: 0.100 para 10%', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Comisión de Compra (en decimal, ej: 0.100 = 10%)')),
                ('comision_venta', models.DecimalField(decimal_places=3, default=0, help_text='Ingrese el valor en decimal (entre 0 y 1). Ejemplo: 0.100 para 10%', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Comisión de Venta (en decimal, ej: 0.100 = 10%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activa', models.BooleanField(default=True, verbose_name='Tasa activa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasas', to='monedas.moneda', verbose_name='Moneda')),
                ('ultimo_editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasas_editadas', to=settings.AUTH_USER_MODEL, verbose_name='Último editor')),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'db_table': 'tasas_cambio',
                'permissions': [('crear_tasa', 'Puede crear tasas de cambio'), ('editar_tasa', 'Puede editar tasas de cambio'), ('activar_tasa', 'Puede activar/desactivar tasas de cambio'), ('ver_tasa', 'Puede ver tasas de cambio')],
                'default_permissions': [],
            },
        ),
    ]
