# Generated by Django 5.2.5 on 2025-08-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula_identidad',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_cedula',
            field=models.CharField(choices=[('RUC', 'Registro Único de Contribuyente'), ('CI', 'Cédula de Identidad')]),
        ),
    ]
