# Generated by Django 5.2.5 on 2025-08-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_cedula_identidad_alter_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula_identidad',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_cedula',
            field=models.CharField(choices=[('RUC', 'Registro Único de Contribuyente'), ('CI', 'Cédula de Identidad')], max_length=3),
        ),
    ]
