# Generated by Django 5.2.5 on 2025-08-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_crear_grupos_predefinidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Indica si el usuario está bloqueado en el sistema'),
        ),
    ]
