# Generated by Django 5.2.5 on 2025-08-21 23:55

from django.db import migrations

def agregar_grupo_operador(apps, schema_editor):
    # Obtenemos el modelo Group
    Group = apps.get_model('auth', 'Group')
    
    # Creamos el grupo operador si no existe
    Group.objects.get_or_create(name='operador')

def eliminar_grupo_operador(apps, schema_editor):
    # Obtenemos el modelo Group
    Group = apps.get_model('auth', 'Group')
    
    # Eliminamos el grupo operador
    Group.objects.filter(name='operador').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_agregar_campo_bloqueado'),
    ]

    operations = [
        migrations.RunPython(agregar_grupo_operador, eliminar_grupo_operador),
    ]
