# Generated by Django 5.2.6 on 2025-09-04 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipoDocCliente', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('RUC', 'Registro Único de Contribuyente')], max_length=3)),
                ('docCliente', models.CharField(max_length=20, unique=True)),
                ('correoElecCliente', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('tipoCliente', models.CharField(choices=[('F', 'Persona Física'), ('J', 'Persona Jurídica')], max_length=1)),
                ('direccion', models.TextField(max_length=100)),
                ('ocupacion', models.CharField(max_length=30)),
                ('declaracion_jurada', models.BooleanField(default=False)),
                ('segmento', models.CharField(choices=[('minorista', 'Minorista'), ('corporativo', 'Corporativo'), ('vip', 'VIP')], default='minorista', max_length=20)),
                ('beneficio_segmento', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'permissions': [('gestion', 'Puede gestionar clientes (crear y editar)')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='SegmentacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_beneficio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Segmentación de Cliente',
                'verbose_name_plural': 'Segmentaciones de Clientes',
                'db_table': 'segmentacion_clientes',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Relación Usuario-Cliente',
                'verbose_name_plural': 'Relaciones Usuario-Cliente',
                'db_table': 'usuarios_clientes',
                'default_permissions': [],
            },
        ),
    ]
