# Generated by Django 5.2.6 on 2025-10-31 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(related_name='clientes_operados', to=settings.AUTH_USER_MODEL),
        ),
    ]
