# Generated by Django 5.2.5 on 2025-08-25 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(related_name='clientes_operados', through='clientes.UsuarioCliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios operadores'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariocliente',
            unique_together={('usuario', 'cliente')},
        ),
    ]
