# Generated by Django 5.2.5 on 2025-08-22 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_usuario_cliente_relation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='declaracion_jurada',
            field=models.BooleanField(default=False, verbose_name='Declaración Jurada Firmada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='usuarios',
            field=models.ManyToManyField(related_name='clientes_operados', through='clientes.UsuarioCliente', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios operadores'),
        ),
    ]
