# Generated by Django 5.2.6 on 2025-09-04 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_segmentacioncliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentacionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_beneficio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Segmentación de Cliente',
                'verbose_name_plural': 'Segmentaciones de Clientes',
                'db_table': 'segmentacion_clientes',
            },
        ),
    ]
