# Generated by Django 5.2.5 on 2025-08-22 13:34

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0002_crear_rol_administrador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
