# Generated by Django 5.2.6 on 2025-09-04 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cotizacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cotización')),
                ('id_moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='monedas.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_cotizacion'],
                'unique_together': {('id_moneda', 'fecha_cotizacion')},
            },
        ),
    ]
