# Generated by Django 5.2.6 on 2025-09-05 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='segmentacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.segmentacioncliente', verbose_name='Segmentación de Cliente'),
        ),
    ]
