# Generated by Django 5.2.6 on 2025-09-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='precio_venta',
        ),
    ]
