# Generated by Django 5.2.6 on 2025-09-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('simbolo', models.CharField(max_length=3, unique=True)),
                ('activa', models.BooleanField(default=True)),
                ('tasa_base', models.IntegerField(default=0)),
                ('comision_compra', models.IntegerField(default=0)),
                ('comision_venta', models.IntegerField(default=0)),
                ('decimales', models.SmallIntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'monedas',
                'permissions': [('gestion', 'Puede gestionar monedas (crear y editar)'), ('activacion', 'Puede activar/desactivar monedas'), ('cambiar_tasa', 'Puede cambiar la tasa base de una moneda'), ('cambiar_decimales', 'Puede cambiar el número de decimales de una moneda'), ('cambiar_comisiones', 'Puede cambiar las comisiones de compra y venta de una moneda')],
                'default_permissions': [],
            },
        ),
    ]
