# Generated by Django 5.2.5 on 2025-08-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(error_messages={'unique': 'Ya existe una moneda con este nombre.'}, max_length=100, unique=True, verbose_name='Nombre de la moneda')),
                ('simbolo', models.CharField(error_messages={'max_length': 'El símbolo de la moneda no puede tener más de 3 caracteres.', 'unique': 'Ya existe una moneda con este símbolo.'}, max_length=3, unique=True, verbose_name='Símbolo de la moneda')),
                ('activa', models.BooleanField(default=True, help_text='Determina si la moneda está activa para operaciones', verbose_name='Moneda activa')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'db_table': 'monedas',
                'permissions': [('crear', 'Puede crear monedas'), ('editar', 'Puede editar monedas'), ('activacion', 'Puede activar/desactivar monedas')],
                'default_permissions': [],
            },
        ),
    ]
