# Generated by Django 5.2.5 on 2025-08-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneda',
            options={'default_permissions': [], 'permissions': [('crear', 'Puede crear monedas'), ('editar', 'Puede editar monedas'), ('activacion', 'Puede activar/desactivar monedas'), ('cambiar_tasa', 'Puede cambiar la tasa base de una moneda'), ('cambiar_decimales', 'Puede cambiar el número de decimales de una moneda')], 'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AddField(
            model_name='moneda',
            name='decimales',
            field=models.IntegerField(default=3, help_text='Número de decimales para la moneda', verbose_name='Decimales'),
        ),
        migrations.AddField(
            model_name='moneda',
            name='tasa_base',
            field=models.IntegerField(default=0, help_text='Tasa de cambio base de la moneda a guaraníes', verbose_name='Tasa base'),
        ),
    ]
