# Generated by Django 5.2.6 on 2025-09-20 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segmentacion', models.CharField(choices=[('VIP', 'VIP'), ('CORPORATIVO', 'Corporativo'), ('MINORISTA', 'Minorista')], max_length=20, verbose_name='Segmentación')),
                ('porcentaje_limite', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje límite')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitaciones', to='monedas.moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Limitación',
                'verbose_name_plural': 'Limitaciones',
                'db_table': 'limitaciones',
                'unique_together': {('moneda', 'segmentacion')},
            },
        ),
    ]
