# Generated by Django 5.2.6 on 2025-09-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='comision_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Comisión de compra'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='comision_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Comisión de venta'),
        ),
    ]
