# Generated by Django 5.2.6 on 2025-09-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monedas', '0002_alter_moneda_comision_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneda',
            name='tasa_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Tasa base'),
        ),
    ]
