# Generated by Django 5.2.6 on 2025-09-24 01:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
        ('monedas', '0002_limitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimiteGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_diario', models.IntegerField(default=90000000, help_text='Límite diario global en guaraníes')),
                ('limite_mensual', models.IntegerField(default=450000000, help_text='Límite mensual global en guaraníes')),
                ('fecha_inicio', models.DateField(default=datetime.date.today, help_text='Fecha desde cuando rige este límite')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha hasta cuando rige este límite (opcional)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este límite está vigente')),
            ],
            options={
                'verbose_name': 'Límite Global',
                'verbose_name_plural': 'Límites Globales',
                'db_table': 'limite_global',
                'permissions': [('gestion', 'Puede gestionar límites globales')],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='ConsumoLimiteCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today, help_text='Fecha del registro de consumo')),
                ('consumo_diario', models.IntegerField(default=0, help_text='Consumo acumulado del día en guaraníes')),
                ('consumo_mensual', models.IntegerField(default=0, help_text='Consumo acumulado del mes en guaraníes')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_limite', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Consumo de Límite Cliente',
                'verbose_name_plural': 'Consumos de Límites Clientes',
                'db_table': 'consumo_limite_cliente',
                'default_permissions': [],
                'unique_together': {('cliente', 'fecha')},
            },
        ),
    ]
