# Generated by Django 5.2.6 on 2025-09-19 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('monedas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('billetera_electronica', 'Billetera Electrónica'), ('cheque', 'Cheque')], max_length=25, unique=True, verbose_name='Tipo de Medio de Pago')),
                ('activo', models.BooleanField(default=True, help_text='Determina si este medio de pago está activo y disponible para usar', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('monedas', models.ManyToManyField(help_text='Monedas soportadas por este medio de pago', related_name='medios_pago', to='monedas.moneda', verbose_name='Monedas')),
            ],
            options={
                'verbose_name': 'Medio de Pago',
                'verbose_name_plural': 'Medios de Pago',
                'db_table': 'medios_pago',
                'ordering': ['tipo'],
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='MedioPagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_tc', models.CharField(blank=True, choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares')], help_text='Solo aplicable para tarjetas de crédito. Debe ser PYG o USD', max_length=3, null=True, verbose_name='Moneda para Tarjeta de Crédito')),
                ('numero_tarjeta', models.CharField(blank=True, help_text='Número de la tarjeta de crédito (16 dígitos)', max_length=20, null=True, verbose_name='Número de Tarjeta')),
                ('cvv_tarjeta', models.CharField(blank=True, help_text='Código de verificación de la tarjeta (3 dígitos)', max_length=3, null=True, verbose_name='CVV')),
                ('nombre_titular_tarjeta', models.CharField(blank=True, help_text='Nombre completo del titular como aparece en la tarjeta', max_length=100, null=True, verbose_name='Nombre del Titular de la Tarjeta')),
                ('fecha_vencimiento_tc', models.CharField(blank=True, help_text='Fecha de vencimiento de la tarjeta de crédito (MM/AA)', max_length=7, null=True, verbose_name='Fecha de Vencimiento')),
                ('descripcion_tarjeta', models.CharField(blank=True, help_text='Descripción breve para identificar la tarjeta (ej: "Tarjeta personal", "Tarjeta de empresa")', max_length=100, null=True, verbose_name='Descripción de la Tarjeta')),
                ('cuenta_destino', models.CharField(blank=True, help_text='Cuenta bancaria donde se acreditarán los pagos con tarjeta', max_length=3, null=True, verbose_name='Cuenta de Destino')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta')),
                ('banco', models.CharField(blank=True, help_text='Nombre del banco donde está la cuenta', max_length=100, null=True, verbose_name='Banco')),
                ('cedula_ruc_cuenta', models.CharField(blank=True, help_text='Cédula de identidad o RUC asociado a la cuenta bancaria', max_length=20, null=True, verbose_name='Cédula o RUC')),
                ('nombre_titular_cuenta', models.CharField(blank=True, help_text='Nombre completo del titular de la cuenta bancaria', max_length=100, null=True, verbose_name='Nombre del Titular de la Cuenta')),
                ('tipo_cuenta', models.CharField(blank=True, help_text='Tipo de cuenta bancaria (corriente, ahorro, etc.)', max_length=50, null=True, verbose_name='Tipo de Cuenta')),
                ('solo_compra_extranjera', models.BooleanField(default=False, help_text='Determina si este medio de pago solo puede usarse para compras extranjeras', verbose_name='Solo para Compra Extranjera')),
                ('moneda_cheque', models.CharField(blank=True, choices=[('PYG', 'Guaraníes'), ('USD', 'Dólares')], help_text='Moneda en la que debe estar emitido el cheque', max_length=3, null=True, verbose_name='Moneda del Cheque')),
                ('activo', models.BooleanField(default=True, help_text='Determina si este medio de pago está activo para este cliente', verbose_name='Activo')),
                ('is_deleted', models.BooleanField(default=False, help_text='Indica si esta configuración fue eliminada lógicamente', verbose_name='Eliminado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medios_pago.mediopago', verbose_name='Medio de Pago')),
            ],
            options={
                'verbose_name': 'Medio de Pago del Cliente',
                'verbose_name_plural': 'Medios de Pago de los Clientes',
                'db_table': 'medios_pago_clientes',
                'ordering': ['cliente__nombre', 'medio_pago__tipo'],
                'default_permissions': [],
                'unique_together': {('medio_pago', 'cliente', 'numero_cuenta'), ('medio_pago', 'cliente', 'numero_tarjeta')},
            },
        ),
        migrations.AddField(
            model_name='mediopago',
            name='clientes',
            field=models.ManyToManyField(help_text='Clientes que pueden usar este medio de pago', related_name='medios_pago', through='medios_pago.MedioPagoCliente', to='clientes.cliente', verbose_name='Clientes'),
        ),
    ]
